[package]
name = "SHC"
version = "0.1.0"
edition = "2024"

# Beispiel: So könnte es in deiner Cargo.toml aussehen
[dependencies]
clap = { version = "4.0", features = ["derive"] }
local-ip-address = "0.5.6" # Welche Version steht hier bei dir?
# ... andere Abhängigkeiten